# --------------------------------------
# -- Service for grpcox
# --------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: pomoday-backend
  namespace: pomoday
  labels:
    run: pomoday
    app: pomoday
spec:
  ports:
    - port: 8080
      name: pomoday
      protocol: TCP
      targetPort: 8080
  selector:
    run: pomoday
